apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castService.name }}
spec:
  selector:
    app: {{ .Values.castService.name }}
  ports:
    - port: {{ .Values.castService.service.port }}
      targetPort: {{ .Values.castService.containerPort }}