apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.castDb.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.castDb.password | quote }}
  POSTGRES_DB: {{ .Values.castDb.database | quote }}
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s/%s" .Values.castDb.username .Values.castDb.password .Values.castDb.name .Values.castDb.database | quote }}