{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-app-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.movies }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.movieService.name }}
                port:
                  number: {{ .Values.movieService.service.port }}
          - path: {{ .Values.ingress.paths.casts }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.castService.name }}
                port:
                  number: {{ .Values.castService.service.port }}
{{- end }}