apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieDb.storage }}