apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movieService.name }}
spec:
  selector:
    app: {{ .Values.movieService.name }}
  ports:
    - port: {{ .Values.movieService.service.port }}
      targetPort: {{ .Values.movieService.containerPort }}