movieService:
  replicaCount: 2
  image:
    tag: ""

castService:
  replicaCount: 2
  image:
    tag: ""

movieDb:
  database: movie_db_prod
  storage: 5Gi

castDb:
  database: cast_db_prod
  storage: 5Gi

ingress:
  host: movie-app.lmarnat.abrdns.com