imagePullPolicy: IfNotPresent

movieService:
  name: movie-service
  replicaCount: 1
  image:
    repository: lmarnat5/movie-service
    pullPolicy: IfNotPresent
  containerPort: 8000
  service:
    port: 8000
  env:
    castServiceHostUrl: "http://cast-service:8000/api/v1/casts/"

castService:
  name: cast-service
  replicaCount: 1
  image:
    repository: lmarnat5/cast-service
    pullPolicy: IfNotPresent
  containerPort: 8000
  service:
    port: 8000

movieDb:
  name: movie-db
  image:
    repository: postgres
    tag: "12.1-alpine"
  port: 5432
  database: movie_db_dev
  username: movie_db_username
  password: movie_db_password
  storage: 1Gi

castDb:
  name: cast-db
  image:
    repository: postgres
    tag: "12.1-alpine"
  port: 5432
  database: cast_db_dev
  username: cast_db_username
  password: cast_db_password
  storage: 1Gi

ingress:
  enabled: true
  className: nginx
  host: movie-app.local
  paths:
    movies: /api/v1/movies
    casts: /api/v1/casts