movieService:
  replicaCount: 2

castService:
  replicaCount: 2

movieDb:
  database: movie_db_prod
  storage: 5Gi

castDb:
  database: cast_db_prod
  storage: 5Gi

ingress:
  host: movie-app.lmarnat.abrdns.com